### ISSUE TITLE
This is a test issue. How can I use github issues as a challenge Q&A platform?

### ISSUE THREAD

**Issue by BenjaminChua** [BenjaminChua/docker-visits#1]
I would need help with testing this platform for Q&A. What are your thoughts?

**Comment by SLSC94** [comment]
test comment #1

**Comment by BenjaminChua** [comment]
Hi thanks for testing

**Comment by khaixcore** [comment]
test comment #2 with mention @BenjaminChua @SLSC94 

example screenshot test
![logo_226_300](https://user-images.githubusercontent.com/28260906/87763214-00ceaf80-c847-11ea-8b39-f41a1146dd47.png)

**Comment by khaixcore** [comment]
looks good, quiet straight forward platform if user run into issues.

**Comment by BenjaminChua** [comment]
yea i think this is a good platform. Would need your help to answer the questions.
